# Generated by Django 4.1.2 on 2023-01-31 12:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='static/blogs_img/default.jpg', upload_to='static/blogs_img/')),
                ('date_created', models.DateField(auto_now=True)),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='static/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='MxikOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MxikObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mxik_input', models.FileField(blank=True, null=True, upload_to='static/mxik/')),
                ('mxik_output', models.FileField(blank=True, null=True, upload_to='')),
                ('mxik_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mxikoption')),
            ],
        ),
    ]
