# Generated by Django 4.1.2 on 2023-01-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxikobject',
            name='mxik_options',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.mxikoption'),
            preserve_default=False,
        ),
    ]
